### ISSUE TITLE
Importer does not give a error if the files haven't been converted

### ISSUE THREAD

**Issue by Rumialumia** [Markemp/Cryengine-Importer#9]
Steps to reproduce.
1.Open Blender
2.Import Mech
3.Select a unconverted asset
Blender should then open the file but not display any geometry as its a unconverted file. No errors are displayed.

**Comment by Markemp** [comment]
Updated to display an error if the program can't import the armature. This is most likely due to the <mech>.dae file not existing in the body directory, which is probably because the files weren't converted using Cryengine Converter.

I forgot to increment the version number, so it still exists at the same version  But the .zip file can be imported into Blender 3.0+ and it should still work fine.
